apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    service: postgres
spec:
  selector:
    service: postgres
  type: {{ .Values.service.databaseServiceType }}
  ports:
  - port: {{ .Values.service.databasePort }}
