apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    service: server
spec:
  selector:
    app: server
  type: {{ .Values.service.serverServiceType }}
  ports:
  - port: {{ .Values.service.serverPort }}
    targetPort: {{ .Values.service.serverTargetPort }}
    protocol: TCP