name: Build and Push

# Controls when the action will be run. Triggers the action on push or pull requests events.
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # build job
  build:
    # Type of runner the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    # A sequence of tasks to be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build Docker Image
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./services/server
          push: true
          tags: ${{ secrets.DOCKERHUB_REPO_NAME }}/mybooks-server:v1.0.0