name: Build and Push

# Controls when the action will be run. Triggers the action on push or pull requests events.
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # build job
  build:
    # Type of runner the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    # A sequence of tasks to be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build the Docker image
        run: docker build . --file ./services/server/Dockerfile --tag mybooks-server:v1.0.0